Added flags for postgres forwarding and Docker commands
PolideaInternal/airflow-breeze pull request #12
Opened 2019-01-24 14:23 UTC by potiuk

2019-01-24 14:43 UTC, sprzedwojski requested changes

2019-01-24 14:43 UTC, sprzedwojski commented on README.md
> +## Forwarding postgres port to Airflow's Postgres DB
```suggestion
## Forwarding Postgres port to Airflow's Postgres DB
```

2019-01-24 14:43 UTC, sprzedwojski commented on README.md
> +If you want to forward a port for using the webserver, use the --forward-postgres-port flag:
```suggestion
If you want to forward a port for remotely accessing the database, use the --forward-postgres-port flag:
```

2019-01-24 14:43 UTC, sprzedwojski commented on README.md
> +        login to the database as root user with airflow password. Database of airflow
```suggestion
        login to the database as the user "root" with password "airflow". Database of airflow
```

2019-01-24 14:43 UTC, sprzedwojski commented on README.md
> +        is named airflow/airflow.db
```suggestion
        is named "airflow/airflow.db".
```

2019-01-24 14:43 UTC, sprzedwojski commented on run_environment.sh
> +        login to the database as root user with airflow password. Database of airflow
```suggestion
        login to the database as the user "root" with password "airflow". Database of airflow
```

2019-01-24 14:43 UTC, sprzedwojski commented on run_environment.sh
> +        is named airflow/airflow.db
```suggestion
        is named "airflow/airflow.db".
```

2019-01-24 15:59 UTC, potiuk commented
@sprzedwojski - thanks for corrections. It should build now much faster and we can merge it so that we can merge Antek's configuration change.

2019-01-24 16:12 UTC, potiuk commented
@sprzedwojski  -> it builds now :)

2019-01-25 10:18 UTC, sprzedwojski approved these changes

2019-01-25 10:18 UTC, merged